<?php

/* 
 *  Author: Wayne Wang
 *  Website: http://www.bzhy.com
 *  Email: net_use@bzhy.com
 *  Copyright 2010 - 2018 http://www.bzhy.com
 */

$objects =[
    'view' =>[
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCView',
        'tablename' => null,
        'filename'=>'bzhyCView',
        'isinit'=>FALSE,
        'tableAlias'=> null,
    ],
    'sysset' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCSysSet',
        'tablename' => 'system_setting',
        'filename'=>'bzhyCSysSet',  
        'isinit'=>TRUE,
        'tableAlias'=> 'sy',
    ],
    'api' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyAPI',
        'tablename' => null,
        'filename'=>'bzhyAPI',
        'isinit'=>TRUE,
        'tableAlias'=> null,
    ],
    'contact' => [
        'class' => BZHY_OBJECT_CLASS_EXTRA,
        'classname' =>'bzhyCContact',
        'tablename' => 'contact',
        'filename'=>'bzhyCContact',
        'isinit'=>TRUE,
        'tableAlias'=> 'co',
    ],
    'file' => [
        'class' => BZHY_OBJECT_CLASS_EXTRA,
        'classname' =>'bzhyCAttachment',
        'tablename' => 'file',
        'filename'=>'bzhyCAttachment',
        'isinit'=>TRUE,
        'tableAlias'=> 'fi',
    ],
    'idc_room' => [
        'class' => BZHY_OBJECT_CLASS_EXTRA,
        'classname' =>'bzhyCIdc',
        'tablename' => 'idc_room',
        'filename'=>'bzhyCIdc',
        'isinit'=>TRUE,
        'tableAlias'=> 'ir',
    ],
    
    'idc_box' => [
        'class' => BZHY_OBJECT_CLASS_EXTRA,
        'classname' =>'bzhyCIdcbox',
        'tablename' => 'idc_box',
        'filename'=>'bzhyCIdcbox', 
        'isinit'=>TRUE,
        'tableAlias'=> 'ib',
    ],
    'device' => [
        'class' => BZHY_OBJECT_CLASS_EXTRA,
        'classname' =>'CDevice',
        'tablename' => 'deviceinfo',
        'filename'=>'CDevice',
        'isinit'=>TRUE,
        'tableAlias'=> 'de',
    ],
    'host' => [
        'class' => BZHY_OBJECT_CLASS_EXTRA,
        'classname' =>'bzhyCHost',
        'tablename' => 'hosts',
        'filename'=>['bzhyCHostBase','bzhyCHostGeneral','bzhyCHost'],
        'isinit'=>TRUE,
        'tableAlias'=> 'ho',
    ],
    'hostinterface' => [
        'class' => BZHY_OBJECT_CLASS_EXTRA,
        'classname' =>'bzhyCHostInterface',
        'tablename' => 'interface',
        'filename'=>'bzhyCHostInterface',
        'isinit'=>TRUE,
        'tableAlias'=> 'hi',
    ],
    'hostgroup' => [
        'class' => BZHY_OBJECT_CLASS_EXTRA,
        'classname' =>'bzhyCHostGroup',
        'tablename' => 'groups',
        'filename'=>'bzhyCHostGroup', 
        'isinit'=>TRUE,
        'tableAlias'=> 'hg',
    ],
    'usermacro' => [
        'class' => BZHY_OBJECT_CLASS_EXTRA,
        'classname' =>'bzhyCUserMacro',
        'tablename' => 'globalmacro',
        'filename'=>'bzhyCUserMacro',
        'isinit'=>TRUE,
        'tableAlias'=> 'um',
    ],
    'template' => [
        'class' => BZHY_OBJECT_CLASS_EXTRA,
        'classname' =>'bzhyCTemplate',
        'tablename' => 'hosts',
        'filename'=>['bzhyCHostBase','bzhyCHostGeneral','bzhyCTemplate'],
        'isinit'=>TRUE,
        'tableAlias'=> 'tl',
    ],
    'proxy' => [
        'class' => BZHY_OBJECT_CLASS_EXTRA,
        'classname' =>'bzhyCProxy',
        'tablename' => 'hosts',
        'filename'=>['bzhyCProxy'],
        'isinit'=>TRUE,
        'tableAlias'=> 'h',
    ],
    'profile' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCProfile',
        'tablename' => 'profiles',
        'filename'=>'bzhyCProfile',
        'isinit'=>FALSE,
        'tableAlias'=> 'pr',
    ],
    'webuser' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCWebUser',
        'tablename' => 'sessions',
        'filename'=>'bzhyCWebUser',
        'isinit'=>FALSE,
        'tableAlias'=> 'ss',
    ],
    'user' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCUser',
        'tablename' => 'users',
        'filename'=>'bzhyCUser',
        'isinit'=>TRUE,
        'tableAlias'=> 'u',
    ],
    'usergroup' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCUserGroup',
        'tablename' => 'usrgrp',
        'filename'=>'bzhyCUserGroup',
        'isinit'=>TRUE,
        'tableAlias'=> 'g',
    ],
    'relationmap' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'CRelationMap',
        'tablename' => null,
        'filename'=>'bzhyCRelationMap',
        'isinit'=>TRUE,
        'tableAlias'=>null,
    ],
    'usermedia' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCUserMedia',
        'tablename' => 'media',
        'filename'=>'bzhyCUserMedia',
        'isinit'=>TRUE,
        'tableAlias'=>'m',
    ],
    'mediatype' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCMediatype',
        'tablename' => 'media_type',
        'filename'=>'bzhyCMediatype',
        'isinit'=>TRUE,
        'tableAlias'=>'mt',
    ],
    'pagefilter' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCPageFilter',
        'tablename' => null,
        'filename'=>'bzhyCPageFilter',
        'isinit'=>FALSE,
        'tableAlias'=>null,
    ],
    'url' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCUrl',
        'tablename' => null,
        'filename'=>'bzhyCUrl',
        'isinit'=>FALSE,
        'tableAlias'=>null,
    ],
    'link' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCLink',
        'tablename' => null,
        'filename'=>['bzhyCObject','bzhyCTag','bzhyCLink'],
        'isinit'=>FALSE,
        'tableAlias'=>null,
    ],
    'span' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCSpan',
        'tablename' => null,
        'filename'=>['bzhyCObject','bzhyCTag','bzhyCSpan'],
        'isinit'=>FALSE,
        'tableAlias'=>null,
    ], 
    'span' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCDiv',
        'tablename' => null,
        'filename'=>['bzhyCObject','bzhyCTag','bzhyCDiv'],
        'isinit'=>FALSE,
        'tableAlias'=>null,
    ], 
    'pageheader' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCPageHeader',
        'tablename' => null,
        'filename'=>'bzhyCPageHeader',
        'isinit'=>FALSE,
        'tableAlias'=>null,
    ], 
    'users_groups' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>null,
        'tablename' => 'users_groups',
        'filename'=>null,
        'isinit'=>FALSE,
        'tableAlias'=>'ug',
    ], 
    'hosts_groups' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>null,
        'tablename' => 'hosts_groups',
        'filename'=>null,
        'isinit'=>FALSE,
        'tableAlias'=>'hg',
    ], 
    'arrayhelper' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCArrayHelper',
        'tablename' => null,
        'filename'=>'bzhyCArrayHelper',
        'isinit'=>FALSE,
        'tableAlias'=>null,
    ], 
    'html' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCHtml',
        'tablename' => null,
        'filename'=>'bzhyCHtml',
        'isinit'=>FALSE,
        'tableAlias'=>null,
    ], 
    'session' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCSession',
        'tablename' => null,
        'filename'=>'bzhyCSession',
        'isinit'=>FALSE,
        'tableAlias'=>null,
    ], 
    'dbmysqlbackend' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyMysqlDbBackend',
        'tablename' => null,
        'filename'=>['bzhyMysqlDbBackend','bzhyDbBackend'],
        'isinit'=>FALSE,
        'tableAlias'=>null,
    ], 
    'dbpostgresqlbackend' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyPostgresqlDbBackend',
        'tablename' => null,
        'filename'=>['bzhyPostgresqlDbBackend','bzhyDbBackend'],
        'isinit'=>FALSE,
        'tableAlias'=>null,
    ], 
    'dboraclebackend' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyOracleDbBackend',
        'tablename' => null,
        'filename'=>['bzhyOracleDbBackend','bzhyDbBackend'],
        'isinit'=>FALSE,
        'tableAlias'=>null,
    ], 
    'dboraclebackend' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyOracleDbBackend',
        'tablename' => null,
        'filename'=>['bzhyOracleDbBackend','bzhyDbBackend'],
        'isinit'=>FALSE,
        'tableAlias'=>null,
    ], 
    'dbdb2backend' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhySqliteDbBackend',
        'tablename' => null,
        'filename'=>['bzhyDbBackend','bzhyDb2DbBackend'],
        'isinit'=>FALSE,
        'tableAlias'=>null,
    ], 
    'dbsqlitebackend' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhySqliteDbBackend',
        'tablename' => null,
        'filename'=>['bzhyDbBackend','bzhySqliteDbBackend'],
        'isinit'=>FALSE,
        'tableAlias'=>null,
    ], 
    'listitem' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCListItem',
        'tablename' => null,
        'filename'=>['bzhyCObject','bzhyCTag','bzhyCListItem'],
        'isinit'=>FALSE,
        'tableAlias'=>null,
    ], 
    'list' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCList',
        'tablename' => null,
        'filename'=>['bzhyCObject','bzhyCTag','bzhyCList'],
        'isinit'=>FALSE,
        'tableAlias'=>null,
    ], 
    'warning' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCWarning',
        'tablename' => null,
        'filename'=>['bzhyCObject','bzhyCTag','bzhyCDiv','bzhyCWarning'],
        'isinit'=>FALSE,
        'tableAlias'=>null,
    ], 
    'button' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCButton',
        'tablename' => null,
        'filename'=>['bzhyCObject','bzhyCTag','bzhyCButtonInterface','bzhyCButton'],
        'isinit'=>FALSE,
        'tableAlias'=>null,
    ], 
    'profilter' => [
        'class' => BZHY_OBJECT_CLASS_COMMON,
        'classname' =>'bzhyCProfiler',
        'tablename' => null,
        'filename'=>'bzhyCProfiler',
        'isinit'=>FALSE,
        'tableAlias'=>null,
    ], 
    'graph' => [
        'class' => BZHY_OBJECT_CLASS_EXTRA,
        'classname' =>'bzhyCGraph',
        'tablename' => 'graphs',
        'filename'=>['bzhyCGraphGeneral','bzhyCGraph'],
        'isinit'=>FALSE,
        'tableAlias'=>'g',
    ], 
];

return $objects;